name: Push docs to MarkPrompt

on:
  push:
    branches:
      - main

env:
  MARKPROMPT_TOKEN: ${{ secrets.MARKPROMPT_TOKEN }}

jobs:
  upload-docs:
    name: Upload Docs to MarkPrompt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Renamed Docs
        run: |
          find extensions -type f -name "README.md" -print0 | while IFS= read -r -d '' file; do
            parent=$(basename "$(dirname "$file")")
            cp "$file" "$(dirname "$file")/${parent}_extension.md"
          done

      - name: Generate Marketplace File
        run: |
          extensions_list=$(find extensions -type d -mindepth 1 -maxdepth 1 -printf "- %f\n")
          echo '---' > extensions/marketplace.md
          echo 'title: Awell Marketplace' >> extensions/marketplace.md
          echo 'description: The Awell Marketplace lists all available extensions that help you integrate all the apps you already use for CareOps in your care flows.' >> extensions/marketplace.md
          echo '---' >> extensions/marketplace.md
          echo '# Awell Marketplace' >> extensions/marketplace.md
          echo '' >> extensions/marketplace.md
          echo 'The Awell Marketplace lists all available extensions that help you integrate all the apps you already use for CareOps in your care flows. Awell has an integration or extension with the following apps:' >> extensions/marketplace.md
          echo "$extensions_list" >> extensions/marketplace.md

      - name: Zip Docs
        run: zip data.zip $(find extensions -type f -name "*_extension.md")

      - name: Upload docs to MarkPrompt
        run: |
          curl https://api.markprompt.com/v1/train \
          -X POST \
          -H "Authorization: Bearer ${{ env.MARKPROMPT_TOKEN }}" \
          -H "Content-Type: application/zip" \
          --data-binary @data.zip

      - name: Clean Up Copied Files
        run: |
          find extensions -type f -name "*_extension.md" -exec sh -c 'parent=$(basename $(dirname {})); filename=$(basename {}); if [ "$filename" = "${parent}_extension.md" ]; then rm -f {}; fi' \;
          rm extensions/marketplace.md
