name: Test and Package Release

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: yarn install
        run: yarn

      - name: Compile Typescript
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AWELL_EXTENSIONS_CI }}

      - name: Publish to NPM Registry
        run: |
          yarn version -i patch
          yarn npm publish --access public
      - name: Redeploy the extension server
        run: |
          CURRENT_VERSION=$(cat package.json | jq -r '.version')
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.EXTENSION_SERVER_DEPLOY_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/awell-health/awell-extension-server/actions/workflows/update-dependency.yml/dispatches \
            -d '{"ref":"main","inputs":{"dependency":"@awell-health/awell-extensions","version":"'"$CURRENT_VERSION"'"}}'

      - name: Commit and push updated version
        run: |
          git config --global user.name "Awell CI"
          git config --global user.email "ci@awellhealth.com"
          git add package.json .yarn/versions
          git commit -m "ci: bump version"
          git push
